# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SkiSlopePlugin
                                 A QGIS plugin
 Plugin pro vyhledání vhodným míst pro umístění sjezdovek
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-05
        copyright            : (C) 2025 by Tomáš Mlejnek, Jana Tomášková
        email                : mlejntom@cvut.cz, tomasj15@cvut.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

def classFactory(iface):
    from .Ski_Slope_Plugin import SkiSlopePlugin
    return SkiSlopePlugin(iface)
