
"""
/***************************************************************************
 SkiSlopePlugin
                                 A QGIS plugin
 Plugin pro vyhledání vhodným míst pro umístění sjezdovek
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-05
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tomáš Mlejnek, Jana Tomášková
        email                : mlejntom@cvut.cz, tomasj15@cvut.cz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QObject
from qgis.core import QgsProcessingProvider, QgsApplication
from .Ski_Slope_Plugin_dockwidget import SkiSlopePluginDockWidget
from .script_komplet import Model_komplet


class InlineProcessingProvider(QgsProcessingProvider):
    def loadAlgorithms(self):
        self.addAlgorithm(Model_komplet())

    def id(self):
        return "my_models" 

    def name(self):
        return "Ski Slope Plugin"

    def longName(self):
        return self.name()


class SkiSlopePlugin(QObject):
    def __init__(self, iface):
        super().__init__()
        self.iface = iface
        self.provider = None
        self.dock_widget = None

    def initGui(self):
        self.provider = InlineProcessingProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)
        self.dock_widget = SkiSlopePluginDockWidget()
        self.iface.addDockWidget(0, self.dock_widget)

    def unload(self):
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)
        if self.dock_widget:
            self.iface.removeDockWidget(self.dock_widget)